### ISSUE TITLE
Error loading checkpoint

### ISSUE THREAD

**Issue by Iust1n2** [Coderx7/SimpleNet_Pytorch#7]
When I try to load the checkpoint using: 
```
model = SimpleNet()
checkpoint = torch.load("snapshots/simplenetv1/CIFAR10/model_best_2018-05-04_18-30-13.pth")
model.load_state_dict(checkpoint['state_dict'])
```

I get the following error: 
```
RuntimeError: Error(s) in loading state_dict for SimpleNet:
	Missing key(s) in state_dict: "features.0.weight", "features.0.bias", "features.1.weight", "features.1.bias", ... 
        Unexpected key(s) in state_dict: "module.features.0.weight", "module.features.0.bias", "module.features.1.weight", "module.features.1.bias", ...

**Comment by Coderx7** [comment]
This is caused by the `DataParallel` wrapper. you either have to wrap your model with `torch.nn.DataParallel` or simply remove the `module.` prefix from the state_dict keys like this for example: 
```python
checkpoint = torch.load("snapshots/simplenetv1/CIFAR10/model_best_2018-05-04_18-30-13.pth")['state_dict']
state_dict = {k.replace("module.", ""): v for k, v in state_dict.items()}
model.load_state_dict(state_dict)
```
**Edit:** 

I noticed since I added extra dropout layers after all layers in the latest commit(my latest refactorings), you need to remove them to load the weights properly now.

So this should fix your issues and allow you to load the old weights properly: 
```python 
# remove the dropout layers except the ones after maxpools 
def remove_dropout_layers(model):
    features = torch.nn.Sequential()
    prev_layer = None
    i=0
    for layer in model.features.children():
        if isinstance(layer, torch.nn.Dropout2d):
            if not isinstance(prev_layer, torch.nn.MaxPool2d):
                continue
            layer = torch.nn.Dropout2d(0.1)
        prev_layer = layer
        features.add_module(str(i), layer);i+=1
    # assign the updated features
    model.features = features
    return model

checkpoint = torch.load("snapshots/simplenetv1/CIFAR10/model_best_2018-05-04_18-30-13.pth")['state_dict']
# remove the "module." prefix
state_dict = {k.replace("module.", ""): v for k, v in state_dict.items()}
# remove the extra dropouts 
model = remove_dropout_layers(model)
# load the new state_dict into the model
model.load_state_dict(state_dict)
```

you can also checkout the old implementation [(simplenet.py)](https://github.com/Coderx7/SimpleNet_Pytorch/blob/5d13ddbba6ae531ced26469c6b0f0ec18665d5ec/models/simplenet.py) and use that instead

**Comment by Iust1n2** [comment]
Thank you for the quick response! Your work is inspiring!

**Comment by Coderx7** [comment]
@Iust1n2 My pleasure
One more thing to note though, as I have already pointed out in the readme section  [How to Run note#2](https://github.com/Coderx7/SimpleNet_Pytorch/tree/master/cifar#how-to-run-), in order to load the old weights, you have to use the `simplenet_cifar_5m_extra_pool` model definition. after that you should be good to go. 
```python
from simplenet import simplenet_cifar_5m_extra_pool
model = simplenet_cifar_5m_extra_pool(num_classes=10)
# remove prefix and extra dropouts as explained before
# load the state_dict and use the model as you wish
```
the rest is the same as I explained before. 
For training new models, you should not have any issues, you can choose any models, or use the SimpleNet() constructor directly to build your variant.

**Comment by Iust1n2** [comment]
Thanks! Everything is in order now. Just to see if I understand, when you say the old weights, are you referring to the ones saved in the checkpoints in the  simplenetv1 subfolder, the ones that I was trying to load, right? And the new models would be the ones supported with PyTorch (torch hub)? The difference between them would be that the older models have already been trained on cifar10/100 and the new ones are just pretrained on ImageNet?

**Comment by Coderx7** [comment]
My pleasure. 
Yes, That's right.
